### PR TITLE
Feature/rpnv1 722 remove destinations from particles

### PR DESCRIPTION
**Pull request by clstrfsck**

### CODE REVIEW

**Review by Sajjon — APPROVED** [review]
LGTM, but how is the new method:

```java
	@Override
	public Set<EUID> getDestinations() {
		return ImmutableSet.of(this.rri.getAddress().euid());
	}
```

used? Didn't really see the use?

**Review by siy — APPROVED** [review]
LGTM, although many files look like repetition of other PR (#15)

**Comment by clstrfsck** [comment]
> LGTM, but how is the new method (`getDestinations()`) used? Didn't really see the use?

It's the same method that was in `Particle` previously.  Previously all subclasses passed the destination EUIDs into `Particle` constructor, which the class stored in a field, and the method `getDestinations()` in `Particle` just returned that field.

This change computes the EUIDs in the subclasses so that there is no explicit field in Particle for this.

**Comment by clstrfsck** [comment]
Will be merged in #20

**Pull request closed without merging**
