### PR TITLE
Compress json log files automatically using gzip

### PR DESCRIPTION
**Pull request by stuartbain**
Update the logging file pattern to automatically compress rolled over json log files using gzip. This change makes json logging consistent with the standard pattern layout configuration.

### CODE REVIEW

**Review by rvelaz — APPROVED** [review]

**Comment by rvelaz** [comment]
@stuartbain can you create a branch in our repo and create the PR from there?

**Comment by stuartbain** [comment]
Hi @rvelaz, I was following the contribution guidelines by creating a fork and making changes in a fork branch. I'm not a member of the radixdlt team so not sure I can even create a branch in the main repo. Could you confirm that this is what you want me do?

**Comment by rvelaz** [comment]
Hi @stuartbain you can create branches and PRs, so please do that. All the CI pipelines we have expect the branch for the PR to be on the repository.
 I'll review with the team the contributing guidelines.

**Comment by stuartbain** [comment]
```
~/D/radixdlt ❯❯❯ git push -u origin log-json-gzip
remote: Permission to radixdlt/radixdlt.git denied to stuartbain.
fatal: unable to access 'https://github.com/radixdlt/radixdlt.git/': The requested URL returned error: 403
```

**Pull request closed without merging**
