### PR TITLE
Update transaction specs

### PR DESCRIPTION
**Pull request by iamyulong**
Updates transaction specs for:
- https://github.com/radixdlt/radixdlt/pull/379
- https://github.com/radixdlt/radixdlt/pull/380
- https://github.com/radixdlt/radixdlt/pull/386

### CODE REVIEW

**Comment by siy** [comment]
There are new changes in the transaction format pending: https://github.com/radixdlt/radixdlt/pull/386

**Comment by iamyulong** [comment]
Yep, will include that as well :)

**Comment by iamyulong** [comment]
@siy included the last change

**Review by siy — APPROVED** [review]
LGTM

**Pull request merged**
