### PR TITLE
Fixed null error if validatorSet was not set with BFTBuilder

### PR DESCRIPTION
**Pull request by cbisaillon**
Would it be better to just throw an exception if validatorSet is null ?

### CODE REVIEW

**Comment by cbisaillon** [comment]
Why use Builder instead of a normal constructor if all the arguments are required to be non null?

**Comment by talekhinezh** [comment]
> Why use Builder instead of a normal constructor if all the arguments are required to be non null?

Yes, this is a good point. Main reason is that this code is from an older architecture and hasn't been properly refactored yet.

**Comment by cbisaillon** [comment]
Is it ok if I refactor to a constructor ?

**Comment by cbisaillon** [comment]
I'll close this and refactor the class to use a constructor instead of Builder

**Pull request closed without merging**
