### PR TITLE
[DO-122] Enable parallel run on integration tests

### PR DESCRIPTION
**Pull request by muzuke**

### CODE REVIEW

**Comment by muzuke** [comment]
This doesn't seem to have any effect. The build times are the same with previous runs.

**Comment by muzuke** [comment]
@Theoklitos @diegomrsantos Is there any other way to run the integrations tests in parallel?

**Comment by muzuke** [comment]
@diegomrsantos Is there anything that can be done on the CI configuration to leverage more cores? Or should I close this PR?

**Comment by diegomrsantos** [comment]
@muzuke I think @rvelaz mentioned one day that we will need to have our own runners for that.

**Comment by rvelaz** [comment]
We can merge the change, but it won't have any effect until we use different runners

**Comment by diegomrsantos** [comment]
Is this change necessary?

**Comment by diegomrsantos** [comment]
Can we close this pr?

**Pull request closed without merging**
